### PR TITLE
Add ASM magic static component providers

### PR DESCRIPTION
**Pull request by Pyrofab**
Cardinal Components' is already fairly optimized, but I believe we can do better. This PR introduces statically defined component factories, as an alternative to component initialization callbacks. Both can coexist, and a `ComponentType` may be attached statically to some providers and dynamically to others. *The only potentially breaking change is that you can no longer overwrite a component.* (see 
b204e13)

**How it works :**

1. Register your component factory classes in the custom properties of your `fabric.mod.json`:

```json
{
    "custom": {
        "cardinal-components-api:component-factories": [
            "io.github.mymod.MyComponents"
        ]
    }
}
```

2. Annotate dedicated factory methods with relevant information:

```java
public final class MyComponents {
    public static final ComponentType<MyComponent> MY_COMPONENT = ... // same registration as usual
       
    @EntityComponentFactory("mymod:mycomponent")
    public static MyComponent create(LivingEntity e) {
        return new MyEntityComponent(e);
    }
   
    @ItemStackComponentFactory(value = "mymod:mycomponent", item = "minecraft:diamond_sword")
    public static MyComponent create(ItemStack s) {
        return new MyItemComponent(e);
    }
}
```

For more examples, see the [relevant part of the test mod](https://github.com/OnyxStudios/Cardinal-Components-API/blob/asm-madness/src/testmod/java/nerdhub/cardinal/componentstest/CardinalComponentsTest.java).

If you are an API consumer, stop here, everything else will work as usual.

**Implementation details :**

3. CCA scans all the factory methods in `preLaunch`, and collects all the component types to be added to each component provider type. It generates a big `GeneratedComponentContainer` interface that contains getters for every component type :

   ```java
   public interface GeneratedComponentContainer extends ComponentStorage {
       default Component get$mymod$mycomponent() {
           return get(...); // fallback to dynamic resolution
       }
       
       default Component get$othermod$theircomponent() {
           return get(...); // fallback to dynamic resolution
       }
   }
   ```

4. `GeneratedComponentStorage` implementations are dynamically generated, that only have the components for which a factory was registered. The constructor is a sequence of calls to those factories :

   ```java
   public final class GeneratedComponentStorage$Item$minecraft$diamond_sword implements GeneratedComponentContainer {
       private final Component mymod$mycomponent;
       
       public GeneratedComponentStorage$Item$minecraft$diamond_sword(ItemStack stack) {
           this.mymod$mycomponent = MyComponents.create(stack);
       }
       
       public Component get$mymod$mycomponent() {
           return this.mymod$mycomponent;
       }
   }
   ```

5. A `ComponentType` implementation is generated for every statically registered component type :

   ```java
   public final class GeneratedComponentType$mymod$mycomponent extends ComponentType {
       public Component get(Object o) {
           return ((GeneratedComponentStorage)((ComponentProvider)o).getStaticComponents()).get$mymod$mycomponent();
       }
   }
   ```

6. `ComponentRegistry.registerIfAbsent()` calls instantiate the type from the generated class if any, and go through the current code path otherwise.

### CODE REVIEW

**Comment by Boundarybreaker** [comment]
Would it be at all possible to add a component factory for blocks, or is the `BlockComponentProvider` system too limiting for that? There's not really any good way to inject capabilities onto someone else's block.

**Comment by Pyrofab** [comment]
I think the simplest thing I could do would be to provide a generic `ComponentFactory` implementation that takes an identifier, eg. `@GenericComponentFactory(value = <componentid>, target = <targetid>)`. `targetid` would be used by providers to retrieve the generated factories.

**Comment by Boundarybreaker** [comment]
The other question is how to actually access that when getting a BlockComponentProvider. That could *potentially* be ASM'd, but it's difficult because of overriding.

**Comment by Pyrofab** [comment]
Well, I'll merge this now and we'll see how it goes. The generic component factory will be added later in a new `util` module.

**Pull request merged**
